### ISSUE TITLE
Firmware upgrade

### ISSUE THREAD

**Issue by mattradford** [chorankates/h4ck#1]
Hi Conor

Just wondering how you managed the firmware upgrade on the Titan? I've logged into via telnet but can't see a way to do it other than the web interface.

Thanks for documenting this BTW 👍 
Cheers,
Matt

**Comment by chorankates** [comment]
@mattradford - to upgrade the firmware:
- log in as admin
- click 'Settings' in the lower right hand corner
- click 'System Settings' in the left hand column
- click 'Firmware Upgrade' in the right hand column

this is for `2.000.022`, but the process should be similar for other versions.

you can get the latest firmware (`2.000.068`) [here](http://www.hootoo.com/downloads-81-88001-010.html#downloads-2000), you'll need to unrar it before you upload, and have a USB drive plugged in.

all that being said.. i keep getting 'wrong file format' when i try and apply the upgrade - going to keep digging here.

**Comment by mattradford** [comment]
Ah, sorry man, I should have said: done all that and "No available space" error pops up. I get the same output from `df -h` as you, showing zero space. I thought you had a way of upgrading firmware without using the web interface.

Wait a sec, now I see you said:

> and have a USB drive plugged in.

I guess this gets round the "No available space" by using the USB storage. I'll give that a go. Thanks again for writing all this up on Github 👍

**Comment by chorankates** [comment]
@mattradford - oh, sorry missed that part.. yeah, based on the path that it is (attempting) to POST the firmware to, it's using the USB drive as a temporary location to upload the new firmware to:

```
/upload.csp?uploadpath=/data/UsbDisk1/Volume1/.vst/upgrade/&file=<timestamp?>&session=<token>
```

and my pleasure - it's been a lot of fun digging through this thing
